### ISSUE TITLE
Widget does not display data

### ISSUE THREAD

**Issue by quazar-omega** [Vocaloid2048/Genshin-Spirit#5]
![Screenshot_2023-07-22-16-55-57-788_de mm20 launcher2 release-edit](https://github.com/Vocaloid2048/Genshin-Spirit/assets/56311398/c4f0fee4-9e90-4748-8d88-c4f454b0562b)

I just tried the widget but it doesn't look like it's working, I don't know if the problem is in fetching or displaying, any way I can debug this better?

<sup>Thanks for the cool app btw :)</sup>

**Comment by Vocaloid2048** [comment]
Sorry for late reply, it should be happened in Android 13 and newest version, which until now, we still didn't have any great solution of it ... Sorry again.

**Comment by quazar-omega** [comment]
No worries, I understand. Do I leave this open as a tracking issue?

**Comment by Vocaloid2048** [comment]
> No worries, I understand. Do I leave this open as a tracking issue?

Sure and thx for letting us know about it 🙇
